name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1

    - name: define-tag
      id: define-image-tag
      run:
        echo "IMAGE_TAG_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/https-proxy-test:${{ steps.package-version.outputs.current-version}}-$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.define-image-tag.outputs.IMAGE_TAG_NAME}}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      run:
        docker push ${{ steps.define-image-tag.outputs.IMAGE_TAG_NAME}}
